# Generated by Django 4.1.1 on 2022-11-26 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_date']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_date',
            new_name='comment_date',
        ),
    ]
